import type { Lobby } from "../../types";

// ── Mock data (replace with real API calls) ──────────────────────────────────
export const MOCK_LOBBIES: Lobby[] = [
  {
    id: "1",
    userId: "u1",
    title: "Gold-Plat ranked, chill vibes only",
    description: "Looking for a calm Duelist main. Mic required. No tilting.",
    rankMin: "Gold",
    rankMax: "Platinum",
    map: "Ascent",
    rolesNeeded: JSON.stringify(["Duelist"]),
    region: "NA",
    status: "open",
    hostUsername: "NightReaper",
    hostTag: "1337",
    discordLink: "https://discord.gg/example",
    currentPlayers: 4,
    maxPlayers: 5,
    open: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    userId: "u2",
    title: "Diamond grind – serious only",
    description:
      "NA Diamond lobby. Must have 200+ hours. Controller or Initiator.",
    rankMin: "Diamond",
    rankMax: "Ascendant",
    map: "Haven",
    rolesNeeded: JSON.stringify(["Controller", "Initiator"]),
    region: "NA",
    status: "open",
    hostUsername: "SilverArrow",
    hostTag: "9999",
    currentPlayers: 4,
    maxPlayers: 5,
    open: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    userId: "u3",
    title: "EU Silver ranked – for fun",
    description: "Casual Silver lobby in EU. Just here to have a good time.",
    rankMin: "Silver",
    rankMax: "Gold",
    map: "Any",
    rolesNeeded: JSON.stringify(["Any"]),
    region: "EU",
    status: "open",
    hostUsername: "BladeStorm",
    hostTag: "4242",
    currentPlayers: 4,
    maxPlayers: 5,
    open: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    userId: "u4",
    title: "Immortal+ KR server",
    description: "Fast-paced KR lobby. High skill ceiling required.",
    rankMin: "Immortal",
    rankMax: "Radiant",
    map: "Split",
    rolesNeeded: JSON.stringify(["Duelist", "Sentinel"]),
    region: "KR",
    status: "full",
    hostUsername: "ProtoX",
    hostTag: "0001",
    currentPlayers: 5,
    maxPlayers: 5,
    open: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    userId: "u5",
    title: "Bronze beginners welcome",
    description: "Learning the game. Everyone welcome, just be kind.",
    rankMin: "Iron",
    rankMax: "Bronze",
    map: "Bind",
    rolesNeeded: JSON.stringify(["Any"]),
    region: "EU",
    status: "open",
    hostUsername: "FrostByte",
    hostTag: "7777",
    currentPlayers: 3,
    maxPlayers: 5,
    open: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    userId: "u6",
    title: "AP Plat/Diamond ranked queue",
    description: "Consistent teammates wanted. We play Pearl/Lotus mainly.",
    rankMin: "Platinum",
    rankMax: "Diamond",
    map: "Pearl",
    rolesNeeded: JSON.stringify(["Controller"]),
    region: "AP",
    status: "closed",
    hostUsername: "VoidHunter",
    hostTag: "5500",
    currentPlayers: 4,
    maxPlayers: 5,
    open: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
